### ISSUE TITLE
Building syncserver fails

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-local-dev#108]
Not sure if this is related to my environment but when doing `npm run update`, I get this error

```
virtualenv --python=`which python2 python | head -n 1` --no-site-packages ./local
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /Users/vijaybudhram/Desktop/working/fxa-local-dev/syncserver/local/bin/python2.7
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2349, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1239, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 62] Too many levels of symbolic links: '/Users/vijaybudhram/Desktop/working/fxa-local-dev/syncserver/local/bin/python2.7'
make: *** [local/COMPLETE] Error 1
syncserver update failed
```

Additionally, while pm2 says the server has started, the browser log says there is an error connecting to server.

```
1525709596407	Sync.BrowserIDManager	DEBUG	Getting a token
1525709596409	Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: http://localhost:5000/token/1.0/sync/1.5
1525709596409	Services.Common.RESTRequest	DEBUG	GET request to http://localhost:5000/token/1.0/sync/1.5
1525709596416	Services.Common.RESTRequest	DEBUG	GET http://localhost:5000/token/1.0/sync/1.5 503
1525709596416	Common.TokenServerClient	DEBUG	Got token response: 503
1525709596416	Common.TokenServerClient	INFO	Server-reported error: {"location":"body","name":"","description":"Resource is not available"}
1525709596416	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientServerError({"now":"2018-05-07T16:13:16.416Z","message":"Server error.","cause":"general","response_body":"{\"status\": \"error\", \"errors\": [{\"location\": \"body\", \"name\": \"\", \"description\": \"Resource is not available\"}]}","response_headers":{"server":"gunicorn/19.6.0","date":"Mon, 07 May 2018 16:13:21 GMT","connection":"close","content-length":"109","content-type":"application/json; charset=UTF-8","x-weave-timestamp":"1525709601.63","x-timestamp":"1525709601"},"response_status":503}) (resource://services-common/tokenserverclient.js:38:36) JS Stack trace: TokenServerClientServerError@tokenserverclient.js:107:16 < processTokenResponse@tokenserverclient.js:357:19 < onResponse@tokenserverclient.js:291:9 < onStopRequest@rest.js:499:5
1525709596418	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1525709596418	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1525709596418	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: TokenServerClientServerError({"now":"2018-05-07T16:13:16.416Z","message":"Server error.","cause":"general","response_body":"{\"status\": \"error\", \"errors\": [{\"location\": \"body\", \"name\": \"\", \"description\": \"Resource is not available\"}]}","response_headers":{"server":"gunicorn/19.6.0","date":"Mon, 07 May 2018 16:13:21 GMT","connection":"close","content-length":"109","content-type":"application/json; charset=UTF-8","x-weave-timestamp":"1525709601.63","x-timestamp":"1525709601"},"response_status":503}) (resource://services-common/tokenserverclient.js:38:36) JS Stack trace: TokenServerClientServerError@tokenserverclient.js:107:16 < processTokenResponse@tokenserverclient.js:357:19 < onResponse@tokenserverclient.js:291:9 < onStopRequest@rest.js:499:5
1525709596418	Sync.BrowserIDManager	ERROR	Could not authenticate: TokenServerClientServerError({"now":"2018-05-07T16:13:16.416Z","message":"Server error.","cause":"general","response_body":"{\"status\": \"error\", \"errors\": [{\"location\": \"body\", \"name\": \"\", \"description\": \"Resource is not available\"}]}","response_headers":{"server":"gunicorn/19.6.0","date":"Mon, 07 May 2018 16:13:21 GMT","connection":"close","content-length":"109","content-type":"application/json; charset=UTF-8","x-weave-timestamp":"1525709601.63","x-timestamp":"1525709601"},"response_status":503}) (resource://services-common/tokenserverclient.js:38:36) JS Stack trace: TokenServerClientServerError@tokenserverclient.js:107:16 < processTokenResponse@tokenserverclient.js:357:19 < onResponse@tokenserverclient.js:291:9 < onStopRequest@rest.js:499:5
1525709596419	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.network due to previous failure
1525709596419	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1525709596419	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1525709596419	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1525709596420	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms.
1525709596420	Sync.ErrorHandler	ERROR	Sync encountered a login error
1525709596424	Sync.Service	DEBUG	Exception calling WrappedLock: TokenServerClientServerError({"now":"2018-05-07T16:13:16.416Z","message":"Server error.","cause":"general","response_body":"{\"status\": \"error\", \"errors\": [{\"location\": \"body\", \"name\": \"\", \"description\": \"Resource is not available\"}]}","response_headers":{"server":"gunicorn/19.6.0","date":"Mon, 07 May 2018 16:13:21 GMT","connection":"close","content-length":"109","content-type":"application/json; charset=UTF-8","x-weave-timestamp":"1525709601.63","x-timestamp":"1525709601"},"response_status":503}) (resource://services-common/tokenserverclient.js:38:36) JS Stack trace: TokenServerClientServerError@tokenserverclient.js:107:16 < processTokenResponse@tokenserverclient.js:357:19 < onResponse@tokenserverclient.js:291:9 < onStopRequest@rest.js:499:5
```

Sync server log
```
13|sync se | ERROR:tokenserver:Unexpected verification error
13|sync se | Traceback (most recent call last):
13|sync se |   File "/usr/local/lib/python2.7/site-packages/tokenserver/views.py", line 85, in valid_assertion
13|sync se |     assertion = verifier.verify(assertion)
13|sync se |   File "/usr/local/lib/python2.7/site-packages/tokenserver/verifiers.py", line 73, in verify
13|sync se |     data = super(LocalVerifier, self).verify(assertion, audience)
13|sync se |   File "/usr/local/lib/python2.7/site-packages/browserid/verifiers/local.py", line 115, in verify
13|sync se |     cert = self.verify_certificate_chain(certificates, now=now)
13|sync se |   File "/usr/local/lib/python2.7/site-packages/browserid/verifiers/local.py", line 161, in verify_certificate_chain
13|sync se |     root_key = self.supportdocs.get_key(root_issuer)
13|sync se |   File "/usr/local/lib/python2.7/site-packages/browserid/supportdoc.py", line 63, in get_key
13|sync se |     supportdoc = self.get_support_document(hostname)
13|sync se |   File "/usr/local/lib/python2.7/site-packages/browserid/supportdoc.py", line 58, in get_support_document
13|sync se |     raise error
13|sync se | ConnectionError: Failed to GET https://127.0.0.1:9000/.well-known/browserid. Reason: HTTPSConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /.well-known/browserid (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5c6b77fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by rfk** [comment]
> IOError: [Errno 62] Too many levels of symbolic links: '/Users/vijaybudhram/Desktop/working/fxa-local-dev/syncserver/local/bin/python2.7'

This suggests you have a symlink loop somewhere; you could try `rm -rf ./syncserver/local` and see if it'll rebuild cleanly after that.

**Comment by vladikoff** [comment]
We also moved the sync server into a docker container https://github.com/mozilla/fxa-local-dev/blob/master/_scripts/syncserver.sh not sure why it is still using the old version

**Comment by vbudhram** [comment]
> rm -rf ./syncserver/local

That fixed the build issue! Curiously though, I was still getting 

```
13|sync se | ConnectionError: Failed to GET https://127.0.0.1:9000/.well-known/browserid. Reason: HTTPSConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /.well-known/browserid (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5c6b77fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

After changing this [line](https://github.com/mozilla/PyBrowserID/blob/master/browserid/supportdoc.py#L217) to use `http`, and restarting, everything seemed to work properly again. I am a little confused because that line has not changed in 6 years. Is there some other local configuration that might be off?
