### ISSUE TITLE
Unable to sync  - Failed to GET https /.well-known/browserid

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-local-dev#112]
Currently, when attempting to sync using this repo, the sync server returns

```
Traceback (most recent call last):
  File "/Users/vijaybudhram/Desktop/fxa-local-dev/syncserver/local/lib/python2.7/site-packages/tokenserver/views.py", line 110, in _valid_browserid_assertion
    assertion = verifier.verify(assertion)
  File "/Users/vijaybudhram/Desktop/fxa-local-dev/syncserver/local/lib/python2.7/site-packages/tokenserver/verifiers.py", line 92, in verify
    data = super(LocalBrowserIdVerifier, self).verify(assertion, audience)
  File "/Users/vijaybudhram/Desktop/fxa-local-dev/syncserver/local/lib/python2.7/site-packages/browserid/verifiers/local.py", line 115, in verify
    cert = self.verify_certificate_chain(certificates, now=now)
  File "/Users/vijaybudhram/Desktop/fxa-local-dev/syncserver/local/lib/python2.7/site-packages/browserid/verifiers/local.py", line 161, in verify_certificate_chain
    root_key = self.supportdocs.get_key(root_issuer)
  File "/Users/vijaybudhram/Desktop/fxa-local-dev/syncserver/local/lib/python2.7/site-packages/browserid/supportdoc.py", line 63, in get_key
    supportdoc = self.get_support_document(hostname)
  File "/Users/vijaybudhram/Desktop/fxa-local-dev/syncserver/local/lib/python2.7/site-packages/browserid/supportdoc.py", line 58, in get_support_document
    raise error
ConnectionError: Failed to GET https://127.0.0.1:9000/.well-known/browserid. Reason: EOF occurred in violation of protocol (_ssl.c:661)
```

I have tried updating the sync docker startup script to use the new `SYNCSERVER_IDENTITY_PROVIDER` but server still fails to sync.

```
docker run --rm --name syncserver \
  -p 5000:5000 \
  -e SYNCSERVER_PUBLIC_URL=http://localhost:5000 \
  -e SYNCSERVER_IDENTITY_PROVIDER=http://localhost:3030 \
  -e SYNCSERVER_SECRET=5up3rS3kr1t \
  -e SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db \
  -e SYNCSERVER_BATCH_UPLOAD_ENABLED=true \
  -e SYNCSERVER_FORCE_WSGI_ENVIRON=true \
  mozilla/syncserver:latest \
  /usr/local/bin/gunicorn --bind 0.0.0.0:5000 \
  syncserver.wsgi_app
```

A workaround was to change [this](https://github.com/mozilla/PyBrowserID/blob/master/browserid/supportdoc.py#L217) to http and run outside of docker.

**Comment by rfk** [comment]
I guess this broke when we switched syncserver to use its own local BrowserID verifier by default, which means it stopped using the local instance of browserid-verifier that's configured to do lookups over http.  I need to test it end-to-end, by my proposal is to:

* Add an env var to configure the browserid verifier URL for syncserver (https://github.com/mozilla-services/syncserver/pull/127)
* Update this repo so that syncserver uses the locally-running verifier instance (https://github.com/mozilla/fxa-local-dev/pull/114)
* And while we're here, also use the new upstream config option to force http lookups, rather than vlad's custom branch (https://github.com/mozilla/browserid-verifier/issues/106)

@vladikoff sound reasonable?

**Comment by rfk** [comment]
> but I've run out of time to test it end-to-end today.

Actually I found some time, and it does seem to be working correctly :-)
